# Generated by Django 5.0.8 on 2024-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadsession',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
