# Generated by Django 5.0.8 on 2024-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fileuploadsession_total_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadsession',
            name='assembly_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
