# Generated by Django 5.0.8 on 2024-08-08 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fileuploadsession_assembly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadsession',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
