# Generated by Django 5.0.8 on 2024-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fileuploadsession_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadsession',
            name='file_size',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
